services:
  win-compiler:
    container_name: terrain_win_compiler
    image: batonogov/pyinstaller-windows
    volumes:
      # Mount your current directory to the container's source root
      - .:/src/
